version: '2'
services:
    j-elasticsearch:
        container_name: j-elasticsearch
        image: elasticsearch:2.4.0
        # volumes:
        #     - ~/volumes/jhipster/j/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
